services:
  - type: web
    name: slark-portfolio
    env: php
    buildCommand: |
      composer install --optimize-autoloader --no-dev
      php artisan key:generate --force
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://slark-portfolio.onrender.com
